### ISSUE TITLE
Add random access navigation

### ISSUE THREAD

**Issue by wmeints** [wmeints/iskabot#1]
Random Access Navigation is way for us to introduce a dozen ways to propose new sessions for the weekly wednesday sessions without forcing us to use very long dialog trees. 

See this article for more information: https://medium.com/assist/theres-a-dozen-ways-to-order-a-coffee-why-do-dumb-bots-only-allow-one-27230542636d

**Comment by mthmulders** [comment]
Additional information on R.A.N.: http://www.intwixt.com/blog/2017/2/22/guidelines-for-designing-intelligent-bots

**Comment by wmeints** [comment]
Ultimately we need to have a way to keep track of the progress in the chat dialog and a way to keep context information for the user. We want to use Slack as a communication channel, which does not support sessions. So instead of a session ID we're going to use UserID. The reasoning behind this is that no user is going to have two active chats at one time.

One other issue I'm running into with this is that a request/reply pattern for this is hard to get right. Instead I would like to use the two-way channel mechanics provided by slack. 

So let's first fix #4 and see about this after that.

**Comment by mthmulders** [comment]
#7 implemented this feature.
